# Generated by Django 4.0.3 on 2022-04-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeanswer',
            unique_together={('author', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='likequestion',
            unique_together={('author', 'question')},
        ),
    ]
